### ISSUE TITLE
additional files needed: samtools.js, samtools.data, samtools.wasm

### ISSUE THREAD

**Issue by kartiksubbarao** [anderspitman/dantest.iobio.io#1]
In order to run this from my local web server, I needed to download the following files from the qual.iobio.io web site and place them in the top-level directory. Can these be added to (or at least documented in) the github repo:

* https://qual.iobio.io/samtools.js
* https://qual.iobio.io/samtools.data
* https://qual.iobio.io/samtools.wasm

**Comment by anderspitman** [comment]
Hi @kartiksubbarao. Thanks for the report. I added a readme with a bit more information. Just out of curiosity what's your purpose in self-hosting qual.iobio?

**Comment by kartiksubbarao** [comment]
Thanks @anderspitman. It was just a general sense of wanting to run the iobio.io tools locally and minimize dependencies/interactions with a central website.
